id: I4E989499
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:14:40+00:00'
last_modified: '2022-06-09T07:52:36.284409+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20034
  title: སྨན་པ་རྐང་རྗེན་མའི་བོད་སྨན་སྦྱོར་སྡེ་གསར་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    183B:
      image_group_id: I1KG12509
      title: Volume 1 of sman pa rkang rjen ma'i bod sman sbyor sde gsar bsgrigs
      total_pages: 340
      order: 1
      base_file: 183B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
