id: opecha:P007948
initial_creation_type: ocr
source_metadata:
  id: bdr:W20034
  title: སྨན་པ་རྐང་རྗེན་མའི་བོད་སྨན་སྦྱོར་སྡེ་གསར་བསྒྲིགས།
  volume:
    c65ebbe14719428cb3d47a1418fc8276:
      image_group_id: I1KG12509
      title: Volume 1 of sman pa rkang rjen ma'i bod sman sbyor sde gsar bsgrigs
      volume_number: 1
      total_pages: 340
  author: ''
ebook_metadata:
  title: སྨན་པ་རྐང་རྗེན་མའི་བོད་སྨན་སྦྱོར་སྡེ་གསར་བསྒྲིགས།
  author: ''
  sku: P007948
  cover: cover.jpg
  layers:
  - pagination
