id: P007948
initial_creation_type: ocr
source_metadata:
  id: bdr:W20034
  title: སྨན་པ་རྐང་རྗེན་མའི་བོད་སྨན་སྦྱོར་སྡེ་གསར་བསྒྲིགས།
  author: ''
  volumes:
    0db1b22c2b5c4865a8fb846b69b62447:
      image_group_id: I1KG12509
      title: ''
      volume_number: 1
      total_pages: 340
ebook_metadata:
  title: སྨན་པ་རྐང་རྗེན་མའི་བོད་སྨན་སྦྱོར་སྡེ་གསར་བསྒྲིགས།
  author: ''
  sku: P007948
  cover: cover.jpg
  layers:
  - pagination
